### ISSUE TITLE
노트 저장소 퍼블리싱

### ISSUE THREAD

**Issue by YoungseoChoi23** [QRAB-EWHA/Frontend#4]
## Description
노트 저장소 페이지 퍼블리싱

## To-do
- [x] 최근 추가한 노트 퍼블리싱
- [x] 저장된 노트 퍼블리싱
- [x] 컨테이너 hovering 효과 적용
- [x] 카테고리 추가 모달창
- [x] 카테고리 편집 모달창
- [x] 카테고리 삭제 모달창
- [x] 흰색 컨테이너 스크롤 시 어두운 배경 -> 흰 배경으로 전환  
- [x] 노트 추가 모달창
- [x] 노트 요약 모달창
